version: "3"

services:
  lib:
    build:
      context: .
      dockerfile: Dockerfile
    image: tracing
    container_name: django_tracing
    volumes:
      - ./:/app
    env_file:
      - .env
    restart: always

